### ISSUE TITLE
在edge完全无法访问

### ISSUE THREAD

**Issue by Leslie-Wong-H** [chinese-poetry/chinese-poetry.github.io#1]
页面显示为一片空白。。。

**Comment by jackeyGao** [comment]
http://shici.store/huajianji/ 请问这里能打开吗？ 首页直接会跳转到这里， 我只能晚上回家才能用edge 浏览器测试一下。，

**Comment by Leslie-Wong-H** [comment]
版本号：
 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by jackeyGao** [comment]
感谢 ， 刚刚找了一个朋友， 在 Edge 浏览器上是可以打开的， 目测可以工作， 但是她不会看浏览器版本。 

![wechatimg9797](https://user-images.githubusercontent.com/2869650/49056907-82b83200-f238-11e8-8e75-ccb990fbe7fd.jpeg)

你能通过开发者模式， 给一点更多的信息吗？  比如控制台有没有报错？  network 里面有没有404或其它报错？

**Comment by Leslie-Wong-H** [comment]
不知道是不是因为你域名后缀解析的问题？身处校园网，现在用chrome，firefox和edge以及360都登不了那个站点了。。。ping倒是可以拿ip，不过被拒接了——请求超时。
自己再用手机移动网络试了下，解析慢了点，可以登——

**Comment by jackeyGao** [comment]
可能是这个原因， store域名是不是很主流的顶级域.  🙂

**Comment by jackeyGao** [comment]
抱歉， 昨天查了下这个问题， 的确是css兼容性 bug。 这个已经修复了

**Comment by Leslie-Wong-H** [comment]
用ping的IP访问也不行。。。也许是教育网无力吧

O(∩_∩)O
